/**
 * 카탈로그 카드에 한 줄로 붙는 짧은 소개말.
 *
 * 서비스 목록·요금제·가격은 전부 백엔드에서 받아오지만, 이 문구만은 앱에 남겨 둔다.
 * 백엔드 description은 한 문장짜리 한글 설명이라 카드 한 줄(numberOfLines={1})에
 * 넣으면 잘려 나가고, 영어 모드에서도 한글이 그대로 나온다.
 * 여기 없는 서비스는 백엔드 description으로 자연스럽게 넘어간다.
 *
 * 로고(ServiceLogo)와 마찬가지로 새 서비스를 추가할 때 같이 채워 주면 된다.
 */
export const SERVICE_TAGLINES: Record<string, string> = {
  'Netflix': 'Movies, Series, Docs',
  'YouTube Premium': 'Ad-free YT + Music',
  'Disney+': 'Disney, Marvel, Star Wars',
  'Wavve': 'Korean VOD',
  'Tving': 'Original Content',
  'Watcha': 'Movie Streaming',
  'Apple TV+': 'Apple Originals',
  'Coupang Play': 'Coupang Streaming',
  'Amazon Prime Video': 'Amazon Originals',
  'Laftel': 'Anime Streaming',
  'Paramount+': 'CBS, Paramount',
  'Spotify': 'Global Music Streaming',
  'Apple Music': 'Lossless Audio',
  'Melon': '#1 Korean Music',
  'Genie Music': 'KT Music Service',
  'FLO': 'SKT Music Service',
  'YouTube Music': 'YouTube-based Music',
  'VIBE': 'Naver Music',
  'Bugs': 'Hi-Fi Music',
  'Tidal': 'HiFi Streaming',
  'GitHub Copilot': 'AI Coding Assistant',
  'JetBrains All Products': 'IntelliJ, WebStorm',
  'ChatGPT Plus': 'OpenAI GPT-4',
  'Claude Pro': 'Anthropic Claude',
  'Notion': 'All-in-one Workspace',
  'Figma': 'Design & Prototype',
  'Cursor': 'AI Code Editor',
  'Midjourney': 'AI Image Generation',
  'Perplexity Pro': 'AI Search Engine',
  'GitLab': 'DevOps Platform',
  'Replit': 'Cloud IDE',
  'Vercel': 'Frontend Deploy',
  'Netlify': 'Static Hosting',
  'AWS': 'Amazon Cloud',
  'DigitalOcean': 'Cloud Servers',
  'Cloudflare': 'CDN / Security',
  'Microsoft 365': 'Office + OneDrive',
  'Google One': 'Google Storage',
  'Dropbox': 'Cloud Storage',
  'Adobe Creative Cloud': 'Photoshop, Illustrator',
  'Slack': 'Team Messaging',
  'Zoom': 'Video Conferencing',
  'Canva Pro': 'Design Tool',
  'Todoist': 'Task Management',
  'Grammarly': 'Grammar Checker',
  'Miro': 'Online Whiteboard',
  'Linear': 'Issue Tracker',
  'Duolingo Plus': 'Language Learning',
  'LinkedIn Premium': 'Career Network',
  'Coursera Plus': 'Online Courses',
  'Class101': 'Creator Classes',
  '인프런': 'IT / Programming',
  '밀리의 서재': 'E-book Subscription',
  '리디 셀렉트': 'E-book / Web Novel',
  '예스24 크레마클럽': 'E-book Subscription',
  '교보문고 sam': 'E-book Subscription',
  '윌라': 'Audiobook / Class',
  'Kindle Unlimited': 'Unlimited E-books',
  'Audible': 'Audiobooks',
  'Nintendo Switch Online': 'Nintendo Online',
  'PlayStation Plus': 'PS Online + Games',
  'Xbox Game Pass': 'Game Subscription',
  'Discord Nitro': 'HD Stream, Emoji',
  'EA Play': 'EA Game Library',
  'Steam': 'PC Game Platform',
  'Calm': 'Meditation / Sleep',
  'Headspace': 'Meditation Guide',
  'Strava': 'Run / Cycle Tracker',
  'Nike Run Club+': 'Running App',
  'FatSecret Premium': 'Diet / Calorie',
  'The New York Times': 'Global News',
  'Medium': 'Article Platform',
  'The Economist': 'Business Magazine',
  '조선일보 디지털': 'Korean News',
  '중앙일보 디지털': 'Korean News',
  'iCloud+': 'Apple Cloud',
  'pCloud': 'Cloud Storage',
  'MEGA': 'Encrypted Storage',
  'NordVPN': 'VPN Service',
  'ExpressVPN': 'Fast VPN',
  'Surfshark': 'Budget VPN',
  '1Password': 'Password Manager',
  'Bitwarden': 'Open-source Passwords',
  '쿠팡 로켓와우': 'Free Delivery',
  '네이버 플러스 멤버십': 'Naver Pay Rewards',
  '배민클럽': 'Delivery Discount',
  '카카오톡 이모티콘 플러스': 'Unlimited Emoticons',
  'Amazon Prime': 'Free Shipping + Video',
};
