"""add notification delivery fields

Revision ID: 7c908e900ec9
Revises: f1d0bda3e094
Create Date: 2026-07-02 20:03:59.154454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c908e900ec9'
down_revision: Union[str, None] = 'f1d0bda3e094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_settings', sa.Column('push_token', sa.String(length=255), nullable=True))
    op.add_column('notifications', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'delivered_at')
    op.drop_column('notification_settings', 'push_token')
    # ### end Alembic commands ###
