"""add initial_exchange_rate to subscriptions

Revision ID: e7d93653a653
Revises: 2a69c8f11637
Create Date: 2026-03-26 15:52:19.183409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d93653a653'
down_revision: Union[str, None] = '2a69c8f11637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('initial_exchange_rate', sa.Numeric(precision=12, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'initial_exchange_rate')
    # ### end Alembic commands ###
