"""add news_cache table

Revision ID: f1d0bda3e094
Revises: 2570ccef0744
Create Date: 2026-07-02 19:14:50.641058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1d0bda3e094'
down_revision: Union[str, None] = '2570ccef0744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=1000), nullable=False),
    sa.Column('pub_date', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_cache')
    # ### end Alembic commands ###
